version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: mastermarket-db
    restart: always
    environment:
      POSTGRES_USER: mastermarket
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: mastermarket_db
    ports:
      - "5432:5432"
    volumes:
      - mastermarket_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: mastermarket-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://mastermarket:securepassword@db:5432/mastermarket_db
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/static:/app/app/static
    mem_limit: 512m
    memswap_limit: 1g

volumes:
  mastermarket_pgdata:
